name = "zona-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"

# Секрет BOT_TOKEN задать командой:
#   wrangler secret put BOT_TOKEN

[[d1_databases]]
binding = "DB"
database_name = "zona"
database_id = "d7c4de9e-4429-4cf5-8b70-e717b81a60be"
